# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "qr18731.europe-west4.gcp"
user = "test_user"
password = "Test@1020"
role = "public"
warehouse = "PUBLIC_WH"
database = "GENERAL_DB"
schema = "PUBLIC"
